run firmware builds in self hosted pool
rusefi/rusefi pull request #3622
Opened 2021-11-26 20:23 UTC by mck1117

testing for now....

2021-11-27 05:54 UTC, rusefillc requested changes
We cannot just kill GHA runners and rely only on unreliable private runners

At the moment recovering back to slow but reliable GHA would mean complex history digging. We need a smarter way where switch back and forth is much simpler

2021-11-28 01:57 UTC, mck1117 commented
It is true that this could pose a reliability issue for now, but the eventual goal is to have runners in the same pool running on multiple machines in multiple houses, etc.

2021-11-28 02:13 UTC, rusefillc commented
I really do not want to choose between speed and fall back effort. This PR cannot go forward as is.

2021-12-17 14:26 UTC, rusefillc commented on .github/workflows/build-firmware-runners.yaml
> +            hellen81,
that would be the third place for same or similar list, a major copy-pasta :(

2021-12-17 14:26 UTC, rusefillc commented on .github/workflows/build-firmware-runners.yaml
> +            ini-file: rusefi_frankenso_na6.ini
We need to at least move ini file into a separate dictionary not to duplicate it?

2022-02-02 00:06 UTC, closed without merging