Java Console reconnection fixing
rusefi/rusefi pull request #3716
Opened 2021-12-22 22:46 UTC by alxrMironovHome

After this changes JC is reconnecting after the 5s timeout (as planned???)

2021-12-22 23:56 UTC, mck1117 commented on java_console/io/src/main/java/com/rusefi/io/LinkManager.java
> +    private String lastTriedPort;
please explicitly initialize (perhaps to null)

2021-12-23 20:11 UTC, rusefillc commented on java_console/io/src/main/java/com/rusefi/io/LinkManager.java
> +    private boolean isStarted = false;
no reason to change that line

2021-12-23 20:12 UTC, rusefillc commented on java_console/io/src/main/java/com/rusefi/io/LinkManager.java
> +       // connector.restart();
we do not need dead code, please remove if if you are removing it

2022-01-02 18:25 UTC, rusefillc requested changes
this removes LinkConnector#restart usages so let's remove all LinkConnector#restart implementations and code

overall my problem is that I do not understand this change. what is fundamentally different between new code and old code?

2022-01-12 04:33 UTC, merged