detect and ignore doubled trigger edges
rusefi/rusefi pull request #4656
Opened 2022-10-11 18:51 UTC by mck1117

Detect when we get a "doubled edge" trigger input.

Will enable the second check (very wrong tooth timing) later, as it causes problems at the moment.

#987 #2222 #4650

2022-10-13 18:38 UTC, mck1117 commented
this looks also OK, proteus CI still sad 🙁

2022-10-13 22:47 UTC, rusefillc commented
What do we perceive to be root cause here? Is it expected to get double edges or it is some specific hardware issue?

Do we want to changelog this improvement?

2022-10-18 14:31 UTC, rusefillc requested changes

2022-10-18 14:31 UTC, rusefillc commented on firmware/controllers/trigger/trigger_central.cpp
> +bool TriggerCentral::isToothExpectedNow(efitick_t timestamp) {
See open comments on ticket

Please rebase to get green build

2022-10-27 12:59 UTC, rusefillc commented
@ElDominio tell me about 4b11 is it Hall or VR?

2022-11-01 21:34 UTC, rusefillc commented
@mck1117 please blink if alive

2022-11-01 23:34 UTC, mck1117 commented
I'm alive! Was racing this weekend and getting ready before that.

2022-11-06 00:23 UTC, rusefillc commented
What do we perceive to be root cause here? Is it expected to get double edges or it is some specific hardware issue?

Do we want to changelog this improvement?

2022-11-30 22:12 UTC, rusefillc commented
@mck1117 is this abandoned?

2022-12-01 00:15 UTC, ElDominio commented
My only question with this is how do some other ECU companies trigger properly on both edges (no crazy sync loss)

2022-12-01 01:13 UTC, mck1117 commented
> My only question with this is how do some other ECU companies trigger properly on both edges (no crazy sync loss)

sort of unrelated discussed offline re: #4635

2023-01-10 19:20 UTC, mck1117 commented
> What do we perceive to be root cause here? Is it expected to get double edges or it is some specific hardware issue?

It is a case we can detect cheaply, so why not detect it? Perhaps it will be a useful metric to detect issues we know about but haven't narrowed down to a root cause.

2023-01-10 19:25 UTC, rusefillc commented
> > What do we perceive to be root cause here? Is it expected to get double edges or it is some specific hardware issue?
> 
> It is a case we can detect cheaply, so why not detect it? Perhaps it will be a useful metric to detect issues we know about but haven't narrowed down to a root cause.

I like this justification! My preference would be to have this filtering enabled by default but have an option to turn it off, what do you think? I am fine adding the option later myself.

2023-01-10 19:29 UTC, mck1117 commented
> I like this justification! My preference would be to have this filtering enabled by default but have an option to turn it off, what do you think? I am fine adding the option later myself.

Right now it only filters truly doubled edges (no trigger should have 1/2 degree tooth spacing), but sure

2023-01-10 21:07 UTC, merged