Bluetooth initialization order bug fix (and housekeeping)
rusefi/rusefi pull request #6623
Opened 2024-06-16 13:56 UTC by scfrontier

When a baud rate change was requested, we were trying to connect at the new baud rate instead of the current "working" baud rate. This was reporting back to the console as a NAME change failure.

Also moved some code to create a "findBaudIndex" function. This is not necessary but helped me keep things organized.

2024-06-16 21:39 UTC, dron0gus requested changes

2024-06-16 21:39 UTC, dron0gus commented on firmware/console/binary/bluetooth.cpp
> +		efiPrintf("Restarting at %d", baudRates[baudIdx].rate);
%lu instead of %d

2024-06-16 21:54 UTC, rusefillc commented
@scfrontier is there any relation to https://github.com/rusefi/rusefi/pull/6620?

2024-06-16 22:11 UTC, scfrontier commented
I'm not sure about [#6620](https://github.com/rusefi/rusefi/pull/6620), it might be a coincidence, or maybe they saw my post on the forum https://rusefi.com/forum/viewtopic.php?f=4&t=340&p=49653#p49653 and are trying to help.

I am trying to figure out their code changes. I will copy jcor25's code and see what happens.

2024-06-16 22:18 UTC, rusefillc commented
@scfrontier there is some life on the discord server https://github.com/rusefi/rusefi/wiki/Discord

2024-06-17 03:56 UTC, rusefillc commented
@scfrontier there is also the part that #6620 is not in a good place as a PR with all the unrelated changes. Any chance you could decide on best approach in a blean PR?

2024-06-20 03:14 UTC, scfrontier commented
I have not been able to reach jcor on Discord for discussion. This pull request has fewer unrelated changes and fewer file changes. I cannot provide evidence as to which solution is best as they both solve the problem in different ways.

2024-06-20 03:30 UTC, merged